name: Basic Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pymongo flask-bcrypt python-dotenv werkzeug
        pip install flake8 pytest
    
    - name: Check Python syntax
      run: |
        python -m py_compile app.py
        echo "✅ app.py syntax is valid"
    
    - name: Basic linting
      run: |
        flake8 app.py --max-line-length=120 --ignore=E501,W503,E203
        echo "✅ Basic linting passed"
      continue-on-error: true
    
    - name: Check imports
      run: |
        python -c "
        try:
            import flask
            import pymongo
            import os
            print('✅ Required packages can be imported')
        except ImportError as e:
            print(f'❌ Import error: {e}')
            exit(1)
        "
    
    - name: Test Flask app creation
      run: |
        python -c "
        import sys
        import os
        
        # Set test environment
        os.environ['FLASK_ENV'] = 'testing'
        os.environ['MONGODB_URI'] = 'mongodb://localhost:27017/test'
        
        try:
            from flask import Flask
            app = Flask(__name__)
            print('✅ Flask app can be created')
        except Exception as e:
            print(f'❌ Flask app creation failed: {e}')
        "
    
    - name: Run existing tests
      run: |
        if [ -f "run_tests.py" ]; then
          python run_tests.py
          echo "✅ Tests completed"
        else
          echo "ℹ️ No test runner found, skipping tests"
        fi
      continue-on-error: true
    
    - name: Check file structure
      run: |
        echo "📁 Checking project structure..."
        ls -la
        if [ -d "app" ]; then echo "✅ app/ directory exists"; fi
        if [ -d "templates" ]; then echo "✅ templates/ directory exists"; fi
        if [ -d "static" ]; then echo "✅ static/ directory exists"; fi
        if [ -f "requirements.txt" ]; then echo "✅ requirements.txt exists"; fi
        echo "✅ Project structure check completed"